finish
Ramosok/TodoList_React_Redux pull request #1
Opened 2022-01-22 02:33 UTC by Ramosok

2022-01-23 16:23 UTC, adryianSiarheyeu requested changes

2022-01-23 16:23 UTC, adryianSiarheyeu commented on src/pages/TodoList/actions/index.js
> +export const CREATE_TODO =createAction('CREATE_TODO');
use prettier

2022-01-23 16:23 UTC, adryianSiarheyeu commented on src/pages/TodoList/components/TodoEditMode/index.js
> +import PropTypes from "prop-types";
imports could be optimized. 
1. import {Card, TextField, ...etc} from '@mui/material'
2. Sane for Icons

2022-01-23 16:23 UTC, adryianSiarheyeu commented on src/pages/TodoList/containers/TodoListContainer.js
> +    const {todos} = useSelector(state => state.todoManagerList)
use selectors

2022-01-23 16:23 UTC, adryianSiarheyeu commented on src/pages/TodoList/containers/TodoListContainer.js
> +    }, [dispatch, formValues.taskText, handleReset]);
why did you add handleReset to depth?

2022-01-23 16:23 UTC, adryianSiarheyeu commented on src/pages/TodoList/reducers/index.js
> +            const copyTodos = [...state.todos];
use cloneDeep

2022-05-30 09:39 UTC, Ramosok commented
dsfsdfsd

2022-05-30 09:53 UTC, closed without merging